#!/usr/bin/env python3
"""Builds WBE_Review_Condensed_Claim_Map.csv: one row per paragraph in
WBE_Review_WR_Condensed_Draft.md's Parts 1-4, tracing each condensed claim
back to its source-draft section(s) and reference(s)."""
import csv
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "WBE_Review_Condensed_Claim_Map.csv"

FIELDS = ["target_section", "paragraph_id", "condensed_claim", "source_sections", "source_references",
          "evidence_level", "compression_action", "omitted_detail", "SI_destination",
          "full_text_verification_required", "author_review_required"]

ROWS = [
# Part 1
{"target_section": "1.1", "paragraph_id": "P1-1", "condensed_claim": "A treatment-plant concentration is not itself a public-health indicator; it requires inversion through a transformation chain. Recent literature (no normalization consensus; flow sometimes outperforms biomarkers; biofilm decay is a major loss pathway) motivates reframing WBE as an inverse problem.",
 "source_sections": "Ch1 (Introduction), paras 1-2", "source_references": "Boogaerts et al. 2024; Rainey et al. 2023; Jung et al. 2026",
 "evidence_level": "Conceptual synthesis, anchored by abstract-checked findings", "compression_action": "shorten",
 "omitted_detail": "Institutional adoption examples (EU dashboard, China national system), developmental-phase history", "SI_destination": "S1 Supplementary Methods; S4 Existing-review competition matrix",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "1.1", "paragraph_id": "P1-2", "condensed_claim": "WBE reframed as an inverse problem: a source signal is distorted via amplitude, temporal, and spatial mechanisms; recovery requires identifiability; process-informed correction is the proposed remedy where identifiability is poor.",
 "source_sections": "Ch1 paras 3-4 (distortion taxonomy); Ch3 §3.0 (formal statement)", "source_references": "none (this review's own framework)",
 "evidence_level": "Conceptual synthesis (original framework, not evidence-dependent)", "compression_action": "merge",
 "omitted_detail": "Full Y(t)=A(t)[K(t,tau)*X(tau)]+eps(t) equation notation (retained conceptually, not restated symbolically here)", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "1.2", "paragraph_id": "P1-3", "condensed_claim": "This is a narrative synthesis, not yet a systematic/scoping review; evidence identified via targeted web search screened by title/snippet, prioritizing peer-reviewed and institutional sources. Full evidentiary status tracked in companion audit files, not restated per claim.",
 "source_sections": "Ch2 §2.1, §2.2, §2.3 (compressed)", "source_references": "none",
 "evidence_level": "Internal methodological statement", "compression_action": "shorten",
 "omitted_detail": "Full search-query breakdown (20 queries, 5 categories); the Miura/Kitajima internal-inconsistency anecdote; the PMC8772136 excluded-source anecdote", "SI_destination": "S1 Supplementary Methods; S2 Full search strategies",
 "full_text_verification_required": "no", "author_review_required": "yes -- confirm the single evidence-status pointer sentence is sufficient for a journal reviewer rather than needing an inline caveat"},
{"target_section": "1.2", "paragraph_id": "P1-4", "condensed_claim": "Review is scoped to the shared signal-formation/distortion/correction problem across targets, not a catalog of every WBE application.",
 "source_sections": "Ch2 §2.6 (scope boundaries)", "source_references": "none",
 "evidence_level": "Internal methodological statement", "compression_action": "shorten",
 "omitted_detail": "Full application taxonomy (Table 2, 4 inference-goal categories) and developmental-phase table (Table 1)", "SI_destination": "S1 Supplementary Methods (Tables 1-2 content)",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "1.3", "paragraph_id": "P1-5", "condensed_claim": "Four original contributions stated: (1) WBE as inverse problem; (2) amplitude-temporal-spatial taxonomy; (3) normalization as mechanism-specific causal correction; (4) identifiability/uncertainty-aware reconstruction framework. All four target the same recurring overclaiming failure mode.",
 "source_sections": "Ch1 para 5 (three organizing arguments); Ch6 §6.0 (Normalization != reconstruction); Ch7 §7.0 (five-way distinction) -- synthesized as this review's explicit thesis statement, not previously stated together in one place in the source draft", "source_references": "none",
 "evidence_level": "Conceptual synthesis (original framework)", "compression_action": "merge",
 "omitted_detail": "none -- this paragraph is a novel synthesis combining material previously scattered across three chapters, per this round's explicit Part 1.3 instruction", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "yes -- confirm the four-contribution framing as stated matches author intent, since it consolidates content not previously co-located in the source draft"},
# Part 2
{"target_section": "2", "paragraph_id": "P2-1", "condensed_claim": "Population-level WBE inference begins from an underlying (infection/consumption/exposure) state that produces measurable analyte via metabolism and excretion; this relationship is only approximately stable.",
 "source_sections": "Ch3 §3.1 opening", "source_references": "none",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-2", "condensed_claim": "Shedding heterogeneity (right-skewed, over-dispersed across individuals) broadens the effective source pulse -- temporal distortion. Chemical-target excretion depends on dose/route/metabolism; pharmacokinetic correction factors from mismatched populations introduce systematic amplitude bias.",
 "source_sections": "Ch3 §3.1 (shedding heterogeneity, dose/route/PK factor paragraphs)", "source_references": "Miura, Kitajima & Omori 2021 (not named in condensed text, referenced qualitatively only); Boogaerts et al. 2024",
 "evidence_level": "Abstract-checked; Miura et al. flagged internally inconsistent in source", "compression_action": "shorten",
 "omitted_detail": "Specific shedding-duration point estimates (3.4 vs 2.6 log copies/g; 26.0 vs 20-32 day duration) -- deliberately omitted given the flagged inconsistency, per instruction not to let abstract-level evidence be read as more precise than it is", "SI_destination": "S5 Biomarker characteristics",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-3", "condensed_claim": "WBE's asymptomatic/undiagnosed-capture advantage means wastewater and clinical signals do not share a denominator -- an identifiability issue, not a calibration detail.",
 "source_sections": "Ch1 para (WBE advantage); Ch3 §3.1 (asymptomatic/undiagnosed shedding paragraph)", "source_references": "NASEM 2023 [11]",
 "evidence_level": "Institutional guidance support", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no (institutional source, general framing claim)", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-4", "condensed_claim": "Excretion/shedding are distributions, not point values; population-average rates understate right-skewed tail behavior relevant to outbreak-detection sensitivity. Chemical parent-to-metabolite ratio adds further dispersion.",
 "source_sections": "Ch8 §8.2 (inter-individual shedding magnitude, parent-compound-to-metabolite conversion paragraphs) -- pulled forward from Ch8 to Part 2 since it is source-state-level content, not propagation-method content", "source_references": "none directly cited in this paragraph (conceptual synthesis of Ch8's distributional framing)",
 "evidence_level": "Conceptual synthesis", "compression_action": "merge",
 "omitted_detail": "Negative-binomial/log-normal-mixture distributional-form detail; the delta-method-misrepresents-tail-risk point (reserved for Part 5)", "SI_destination": "S8 Uncertainty methods and evidence",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-5", "condensed_claim": "Contributing population is dynamic (commuting, tourism, institutional populations, seasonal movement), not a fixed denominator; estimation/correction methods deferred to Part 4.",
 "source_sections": "Ch6 §6.3 opening framing (population dynamism as a phenomenon, not the correction methods)", "source_references": "none in this paragraph",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "Ammonium/mobile-device dynamic-population correction methods (reserved for Part 4.2, not duplicated here)", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-6", "condensed_claim": "Building plumbing (closest stage to source, most tractable, least studied) sets initial dilution; institutional sources (hospitals, prisons, care facilities) can locally dominate a sub-catchment; finite in-building retention allows early transformation.",
 "source_sections": "Ch3 §3.2 (Building and Local Drainage Processes)", "source_references": "none directly cited",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "Greywater mixing detail; disinfectant/cleaning-chemical inhibition mechanism detail", "SI_destination": "S5 Biomarker characteristics (matrix-effects subsection)",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-7", "condensed_claim": "Non-human/non-ingested sources (unused-medication disposal, veterinary use, environmental AMR contributions) are a further source-adjacent bias no excretion-fraction correction detects.",
 "source_sections": "Ch3 §3.1 (chemical dose/route paragraph, non-human-source clause); Ch6 §6.4-6.5 (non-human source caveats, generalized)", "source_references": "none directly cited",
 "evidence_level": "Conceptual synthesis", "compression_action": "merge",
 "omitted_detail": "Specific AMR source-attribution metagenomic method detail (reserved for Part 7 if drafted)", "SI_destination": "S9 Technology-readiness evidence",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "2", "paragraph_id": "P2-8", "condensed_claim": "The sewer-entry load is already a distorted copy of the true source state before any transport/sampling/analytical process acts on it -- the source-state vs. sewer-entry-load distinction that structures the rest of the review.",
 "source_sections": "Ch3 §3.0 (implied), synthesized as an explicit closing statement for this part", "source_references": "none (this review's own framework)",
 "evidence_level": "Conceptual synthesis (original framework)", "compression_action": "merge",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
# Part 3
{"target_section": "3.1", "paragraph_id": "P3-1", "condensed_claim": "Sewage transit is not a uniform slug; different tributary paths carry independently uncertain residence times; a single sample is a time/path-weighted composite. Residence-time distribution varies with pipe geometry, sediment, pump/storage operation.",
 "source_sections": "Ch4 §4.1 (physical processes paragraph, network-level controls paragraph)", "source_references": "none directly cited in this paragraph",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "3.1", "paragraph_id": "P3-2", "condensed_claim": "Residence-time distribution determines how much a sharp source signal is smeared before observation; reporting without characterizing it is reporting an undisclosed temporal distortion.",
 "source_sections": "Ch3 §3.0 (temporal-distortion definition, generalized to the transport-stage argument)", "source_references": "none",
 "evidence_level": "Conceptual synthesis (original argument, added this round to strengthen Part 3.1)", "compression_action": "merge",
 "omitted_detail": "none material -- this is new connective synthesis, not omitting source content", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "yes -- confirm this added connective paragraph (not present verbatim in the source draft) accurately represents intended emphasis"},
{"target_section": "3.2", "paragraph_id": "P3-3", "condensed_claim": "Physical (dilution, adsorption/desorption, incomplete mixing), chemical (hydrolysis, redox, speciation), and biological (biofilm-mediated RNA loss) processes reshape signal in transit. Biofilm decay is distance/retention-time dependent, making amplitude loss spatially heterogeneous.",
 "source_sections": "Ch4 §4.1 (physical, chemical, biological processes paragraphs)", "source_references": "Zhang et al. 2023; Jung et al. 2026",
 "evidence_level": "Abstract-checked", "compression_action": "shorten",
 "omitted_detail": "Specific 90%-in-2-hours decay figure (Zhang et al.) and specific rate-constant comparisons (Jung et al.) -- both pending full-text confirmation in source, stated qualitatively here rather than with unconfirmed precision", "SI_destination": "S6 Normalization evidence / S1 Supplementary Methods (mechanistic literature)",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "3.2", "paragraph_id": "P3-4", "condensed_claim": "Transformation rate/extent jointly governed by temperature, dissolved oxygen, pH, retention time, pipe geometry, sediment, network design -- properties of the network, not the target analyte.",
 "source_sections": "Ch4 §4.1 (network-level controls paragraph)", "source_references": "none directly cited",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "3.3", "paragraph_id": "P3-5", "condensed_claim": "Sediment-adsorbed target resuspended later produces a signal spike reflecting historical, not concurrent, source material -- a 'memory' effect indistinguishable from a genuine concurrent rise without independent evidence.",
 "source_sections": "Ch4 §4.1 (sedimentation/resuspension clause); Ch6 §6.8 (sediment sequestration and delayed release failure mode)", "source_references": "none directly cited",
 "evidence_level": "Conceptual synthesis", "compression_action": "merge",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "3.4", "paragraph_id": "P3-6", "condensed_claim": "Rainfall is not merely dilution: inflow and infiltration dilute, resuspend sediment, shorten retention time, and shift sub-catchment weighting simultaneously; combined-sewer overflow caps rather than dilutes signal.",
 "source_sections": "Ch4 §4.2 (direct effects of rainfall paragraph)", "source_references": "none directly cited in this specific paragraph (evidence follows in next paragraph)",
 "evidence_level": "Conceptual synthesis (mechanistic argument)", "compression_action": "shorten",
 "omitted_detail": "Darling et al. 2025 rural-sewershed CSO detail (deferred to §3.5); Belgian program's specific scale figures (5M inhabitants, 42 plants, 15 months)", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "3.4", "paragraph_id": "P3-7", "condensed_claim": "This is a correctable, structured bias, not unstructured noise: explicit rainfall correction substantially improved correlation with clinical data in a large multi-plant program. Temperature independently accelerates decay and biofilm activity; rainfall/temperature often co-occur seasonally.",
 "source_sections": "Ch4 §4.2 (Janssens finding paragraph; warm-season effects paragraph)", "source_references": "Janssens et al. 2022 [8]; Guo et al. 2023; Jung et al. 2026",
 "evidence_level": "Abstract-checked (Janssens finding is this review's strongest single piece of process-informed-correction evidence)", "compression_action": "shorten",
 "omitted_detail": "Specific 26C temperature threshold (Guo et al., pending full-text confirmation) -- stated qualitatively", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "3.5", "paragraph_id": "P3-8", "condensed_claim": "Sections 3.1-3.4's distortions are coupled, not independently correctable -- this coupling is the condition under which the inverse problem becomes poorly identified, especially at low sampling frequency.",
 "source_sections": "Ch4 §4.3 opening", "source_references": "none",
 "evidence_level": "Conceptual synthesis (original argument)", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "3.5", "paragraph_id": "P3-9", "condensed_claim": "A fixed correction ratio cannot restore identifiability (flow outperforms biomarkers in some settings, fails under high I&I in others -- evidence of no universal fixed factor, not contradiction). Process-informed correction narrows the solution space, as demonstrated by the one directly-tested case.",
 "source_sections": "Ch4 §4.3 (two practical implications paragraph)", "source_references": "Rainey et al. 2023; Darling et al. 2025; Janssens et al. 2022 [8]",
 "evidence_level": "Abstract-checked", "compression_action": "shorten",
 "omitted_detail": "none material beyond specific correlation figures already omitted", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "3.5", "paragraph_id": "P3-10", "condensed_claim": "The sewer network is an active information filter, not a passive conduit -- this section's core, single-argued conclusion.",
 "source_sections": "Ch4 §4 preamble (sewer-as-active-reactor framing)", "source_references": "none",
 "evidence_level": "Conceptual synthesis (original framing, this review's own)", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
# Part 4
{"target_section": "4.1", "paragraph_id": "P4-1", "condensed_claim": "Sampling mode (grab vs. composite) and timing determine what a single sample can represent, independent of downstream correction; grab is vulnerable to diurnal/storm swings, composite trades resolution for averaging.",
 "source_sections": "Ch5 §5.1-§5.2 (sampling location and mode)", "source_references": "none directly cited in this paragraph",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "Flow- vs time-proportional composite sub-distinction detail; specific sampling-location representativeness studies", "SI_destination": "S1 Supplementary Methods",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "4.1", "paragraph_id": "P4-2", "condensed_claim": "Recovery and inhibition/matrix suppression are mechanistically distinct amplitude-loss terms requiring separate QC. Errors produce three distinct consequences: systematic bias, random error, or information loss. An observation model keeps these from collapsing into one 'uncertainty'.",
 "source_sections": "Ch5 §5.5 (six-concept taxonomy, recovery/inhibition pairing); Ch5 §5.7 (bias/error/information-loss three-way split); Ch5 §5.0 (observation model concept)", "source_references": "Pecson et al. 2021; Zafeiriadou et al. 2024 (both referenced only qualitatively, not named in condensed text)",
 "evidence_level": "Abstract-checked (Pecson et al. interlaboratory finding); conceptual synthesis (three-way taxonomy is this review's own)", "compression_action": "merge",
 "omitted_detail": "Pecson et al.'s specific 36-SOP comparison figures; the six-concept taxonomy's full name list (representativeness/recovery/precision/sensitivity/censoring/replicates) collapsed to the two most load-bearing (recovery, inhibition) for space", "SI_destination": "S1 Supplementary Methods; S5 Biomarker characteristics",
 "full_text_verification_required": "yes", "author_review_required": "yes -- confirm collapsing the six-concept taxonomy to two named concepts (recovery, inhibition) in-text, with the rest implied by the bias/error/information-loss framing, does not lose content needed by Part 5's later cross-references"},
{"target_section": "4.2", "paragraph_id": "P4-3", "condensed_claim": "Flow-based load conversion corrects dilution; flow measurement is imperfect and location-dependent; instantaneous-flow/composite-concentration time mismatch adds further error.",
 "source_sections": "Ch6 §6.2 (flow-based normalization, measurement-imperfection paragraph)", "source_references": "none directly cited in this paragraph",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "none material", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "4.2", "paragraph_id": "P4-4", "condensed_claim": "Flow normalization corrects dilution, not population; census/design/connected populations differ; census normalization misreads real population fluctuation as source-signal change; dynamic estimation adds proxy error and re-identification risk at small scale.",
 "source_sections": "Ch6 §6.3 (census vs. dynamic population)", "source_references": "none directly cited in this paragraph (Baz-Lomba et al. 2019 method detail deliberately not repeated here, per instruction against repeating mass-balance/method detail in Part 2, extended to avoid re-deriving it a third time in Part 4)",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "Baz-Lomba et al. 2019 ammonium-proxy R^2=0.88 finding; Been et al. 2014 ammonium/commuter-pattern finding; Thomas et al. 2017 mobile-device validation study", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "4.2", "paragraph_id": "P4-5", "condensed_claim": "Rainfall/infiltration/industrial discharge each limit flow normalization differently, requiring separate handling; flow outperforms biomarkers in some large multi-site studies, fails under high I&I in others -- a context-dependent applicability condition, not a ranking.",
 "source_sections": "Ch6 §6.2 (combined sewers/I&I paragraph, flow-vs-biomarker comparison paragraph)", "source_references": "Rainey et al. 2023; Darling et al. 2025",
 "evidence_level": "Abstract-checked", "compression_action": "shorten",
 "omitted_detail": "182-community/6-state specific study-design detail; Langeveld et al. 2022 Dutch 9-site study detail", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "yes", "author_review_required": "no"},
{"target_section": "4.3", "paragraph_id": "P4-6", "condensed_claim": "No single population biomarker is universally validated; candidates are proposed, then fail specific criteria independently of one another (creatinine: unstable; cotinine: geographically confounded; PMMoV/crAssphage: inconsistent multi-site performance).",
 "source_sections": "Ch6 §6.4 (chemical biomarkers), §6.5 (microbial biomarkers) -- heavily condensed from full per-biomarker narrative", "source_references": "Chen et al. 2014; Maal-Bared et al. 2023; Dhiyebi et al. 2023 (referenced only qualitatively, not named in condensed text)",
 "evidence_level": "Abstract-checked", "compression_action": "shorten",
 "omitted_detail": "Full seven-criterion evaluation table; caffeine/paraxanthine, ammonium/TKN/TP, HF183/BacHuman/mtDNA candidate detail; all specific correlation-improvement percentages and site counts", "SI_destination": "S5 Biomarker characteristics",
 "full_text_verification_required": "yes", "author_review_required": "yes -- confirm this level of compression (naming only 4 of ~9 candidate biomarkers) is acceptable, or whether 1-2 more named examples should be restored"},
{"target_section": "4.3", "paragraph_id": "P4-7", "condensed_claim": "Fate matching (shared persistence, partitioning, temperature sensitivity) is the mechanistic requirement for a valid ratio; near-LOD denominators destabilize ratios disproportionately in exactly the settings needing stable signal most; a ratio does not automatically recover the source state.",
 "source_sections": "Ch6 §6.6 (ratio normalization and error propagation) -- this review's stated 'principal original contribution' for the normalization chapter", "source_references": "none (this review's own derived proposition)",
 "evidence_level": "Conceptual synthesis (original claim)", "compression_action": "shorten",
 "omitted_detail": "The formal 1/normalizer^2 delta-method derivation; log-transform mitigation discussion; Bayesian joint-latent-variable alternative", "SI_destination": "S6 Normalization evidence; S8 Uncertainty methods",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "4.4", "paragraph_id": "P4-8", "condensed_claim": "Three recurring failure modes: correlated numerator-denominator error (shared aliquot/upstream driver), unstable denominator (near-LOD), event-dependent correction failure (CSO loss, resuspension) -- none correctable by any normalizer choice.",
 "source_sections": "Ch6 §6.8 (When Normalization Fails, condensed from 8 bullet items to 3 highest-priority ones per this round's instruction)", "source_references": "none directly cited in this paragraph",
 "evidence_level": "Conceptual synthesis", "compression_action": "shorten",
 "omitted_detail": "5 of 8 original failure-mode bullets (irreversible degradation, unknown non-human sources, spatial mixing/non-identifiability, structural-model misspecification, target/normalizer structurally different fate as a standalone bullet -- the latter folded into §4.3's fate-matching paragraph instead)", "SI_destination": "S6 Normalization evidence",
 "full_text_verification_required": "no", "author_review_required": "yes -- confirm the 3 retained failure modes are the correct highest-priority subset; the 5 omitted modes are listed above for author check against the original 8"},
{"target_section": "4.4", "paragraph_id": "P4-9", "condensed_claim": "Core proposition, stated once and preserved near-verbatim: normalization is a mechanism-specific correction, not reconstruction of the source state; it works only when three joint conditions hold; otherwise it is a differently, and potentially more confidently, distorted signal.",
 "source_sections": "Ch6 §6.0 (boxed 'Normalization != reconstruction' proposition) -- this is the chapter's central claim, carried forward near-verbatim per explicit instruction", "source_references": "none (this review's own proposition)",
 "evidence_level": "Conceptual synthesis (Original Contribution #3, stated in full)", "compression_action": "retain",
 "omitted_detail": "none -- this is the one proposition this round's instruction explicitly required to survive at full strength", "SI_destination": "none",
 "full_text_verification_required": "no", "author_review_required": "no"},
{"target_section": "4.4 / Table 2", "paragraph_id": "P4-10", "condensed_claim": "Table 2 consolidates 4 normalization strategies (flow, census population, dynamic population, biomarker ratio) against corrected mechanism, required assumption, and residual uncertainty.",
 "source_sections": "Ch6 Table 3 (original 11-row normalization matrix), condensed to 4 strategy-class rows", "source_references": "same set as P4-3 through P4-7 (Rainey et al. 2023; Darling et al. 2025; Chen et al. 2014; Maal-Bared et al. 2023; Dhiyebi et al. 2023)",
 "evidence_level": "Abstract-checked (table synthesizes paragraphs above)", "compression_action": "merge",
 "omitted_detail": "7 of 11 original per-biomarker rows (creatinine, cotinine/5-HIAA, caffeine/paraxanthine, ammonium/TKN/TP, PMMoV, crAssphage, HF183/BacHuman/mtDNA as separate rows) -- collapsed into the single 'biomarker ratio' row's general fate-matching requirement", "SI_destination": "S6 Normalization evidence (full 11-row table retained there)",
 "full_text_verification_required": "yes", "author_review_required": "yes -- confirm 4-row table density is acceptable for a Water Research submission table, or whether 1-2 named-biomarker example rows should be restored for concreteness"},
]

def main():
    with open(OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(ROWS)
    print(f"Wrote {len(ROWS)} rows to {OUT}")

if __name__ == "__main__":
    main()
