#!/usr/bin/env python3
"""Builds WBE_Review_Critical_Claim_Verification_Queue.csv: the 9 Critical
(P0) + 7 High (P1) rows from WBE_Review_Condensed_Claim_Map.csv, expanded
into a full verification-task record per row, per this round's 18-field
spec. Also computes and prints which Moderate-tier rows qualify as P2 by
category, for the Evidence Recovery Plan to reference (not expanded to
full rows here -- see that document's own P2/P3 forward-queue section)."""
import csv
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "WBE_Review_Critical_Claim_Verification_Queue.csv"

FIELDS = ["priority", "target_section", "paragraph_id", "exact_claim", "claim_type", "current_reference",
          "current_evidence_level", "current_support_scope", "identified_overextension", "evidence_needed",
          "preferred_evidence_type", "preferred_study_design", "minimum_number_of_settings",
          "database_search_concepts", "candidate_search_query", "full_text_required",
          "decision_if_unresolved", "status"]

ROWS = [
{"priority": "P0", "target_section": "3.2", "paragraph_id": "P3-3",
 "exact_claim": "Sewer biofilms are an active sink for viral RNA rather than an inert surface; laboratory reactor studies report substantial RNA loss within hours of biofilm exposure, and combined batch-decay/pipeline-simulator work identifies microbial activity, rather than chemical hydrolysis, as the dominant driver of that loss, with decay increasing measurably as a function of transport distance.",
 "claim_type": "Mechanistic", "current_reference": "[16] Zhang et al. 2023; [9] Jung et al. 2026",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Each study supports its own lab-reactor/simulator finding; not yet confirmed this generalizes beyond the specific conditions tested",
 "identified_overextension": "None found -- condensed text already avoids the unconfirmed 90%-in-2-hours figure; the mechanistic claim itself needs direct experimental confirmation, not just abstract-level trust",
 "evidence_needed": "Full text confirming experimental design, biofilm colonization method, and whether microbial-activity-dominance was directly measured (e.g., biocide-inhibition control) rather than inferred",
 "preferred_evidence_type": "Primary experimental study with direct mechanistic manipulation (biocide/sterilization control arm)",
 "preferred_study_design": "Controlled laboratory reactor or pipeline-simulator experiment with a microbial-activity-inhibited control arm",
 "minimum_number_of_settings": "1 (mechanism); 2+ preferred for triangulation",
 "database_search_concepts": "sewer biofilm; SARS-CoV-2 RNA decay; wastewater pipe reactor; microbial degradation wastewater",
 "candidate_search_query": '("sewer biofilm" OR "pipe biofilm") AND ("RNA decay" OR "viral RNA degradation") AND (wastewater OR sewer)',
 "full_text_required": "yes",
 "decision_if_unresolved": "narrow -- if full text not obtained, narrow to 'laboratory studies report...' explicitly flagged as lab-condition-specific, not confirmed generalizable to field sewers",
 "status": "Pending full-text acquisition"},
{"priority": "P0", "target_section": "3.4", "paragraph_id": "P3-6",
 "exact_claim": "Rainfall is not merely dilution. It enters sewer networks through two structurally different pathways... that together dilute measured concentration, but also resuspend settled sediment, shorten hydraulic retention time..., and shift the relative contribution of different sub-catchments to the composite signal.",
 "claim_type": "Mechanistic", "current_reference": "None directly cited in this paragraph (evidence follows in P3-7)",
 "current_evidence_level": "Conceptual synthesis based on preceding process evidence",
 "current_support_scope": "Not applicable -- mechanism statement, not yet evidence-anchored in this specific paragraph",
 "identified_overextension": "None identified -- paragraph is explicitly a mechanism statement, not a citation-bearing empirical claim",
 "evidence_needed": "Direct hydraulic/water-quality studies demonstrating each named sub-mechanism (sediment resuspension during storms; retention-time shortening; sub-catchment weight shift) individually",
 "preferred_evidence_type": "Field hydraulic monitoring study with paired dry/wet-weather sampling",
 "preferred_study_design": "Paired or multi-event field study measuring flow, retention time, and sediment resuspension under both dry and wet conditions",
 "minimum_number_of_settings": "2 (to distinguish general mechanism from one network's specific behavior)",
 "database_search_concepts": "combined sewer overflow; inflow infiltration; sediment resuspension storm; hydraulic retention time rainfall",
 "candidate_search_query": '("inflow and infiltration" OR "combined sewer overflow") AND ("sediment resuspension" OR "retention time") AND (wastewater OR sewer)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain -- this is an established sanitary/environmental engineering mechanism independent of WBE-specific literature; if WBE-specific confirmation is not found, cite general hydraulic-engineering literature explicitly rather than implying WBE-specific validation",
 "status": "Pending targeted search (Addendum module 2)"},
{"priority": "P0", "target_section": "3.4", "paragraph_id": "P3-7",
 "exact_claim": "A large multi-plant national wastewater surveillance program found that explicitly correcting concentration data for rainfall impact substantially improved correlation with independent clinical case counts relative to uncorrected data... direct evidence that rainfall behaves as a correctable, structured bias.",
 "claim_type": "Empirical/performance", "current_reference": "[8] Janssens et al. 2022",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Single national program (Belgium); 'substantially improved' not quantified in condensed text; generalizability to other countries/climates not established",
 "identified_overextension": "None found in current text (already hedged as 'one case in this evidence base'); but the underlying single-study status is a structural gap given this is the review's single strongest process-informed-correction evidence anchor",
 "evidence_needed": "Full text confirming actual correlation-improvement magnitude, statistical significance, and whether the finding replicates in a second country/climate",
 "preferred_evidence_type": "Primary empirical study, ideally 2+ independent countries/programs",
 "preferred_study_design": "Before/after or paired comparison of rainfall-corrected vs. uncorrected wastewater-clinical correlation",
 "minimum_number_of_settings": "2 (currently only 1 -- Belgium)",
 "database_search_concepts": "rainfall correction wastewater surveillance; wet weather wastewater signal correction; SARS-CoV-2 wastewater rainfall",
 "candidate_search_query": '(wastewater surveillance) AND (rainfall OR "wet weather") AND (correction OR adjustment) AND (correlation OR validation)',
 "full_text_required": "yes",
 "decision_if_unresolved": "narrow -- if no second setting is found, narrow text to 'In the studied Belgian program...' per the cross-city evidentiary rule",
 "status": "Pending full-text acquisition + targeted search for a second setting"},
{"priority": "P0", "target_section": "3.5", "paragraph_id": "P3-9",
 "exact_claim": "...flow normalization outperforming biomarker normalization in some large multi-site comparisons... while becoming unreliable under substantial inflow and infiltration in others...: the two findings together indicate that no single fixed correction factor is identifiable across all hydraulic conditions.",
 "claim_type": "Cross-site generalization", "current_reference": "[13] Rainey et al. 2023; [3] Darling et al. 2025",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Each study supports its own single condition (Rainey: 182 communities/6 states; Darling: rural, high-I&I sewersheds); 'no single fixed factor identifiable across all conditions' is this review's own synthesis across exactly 2 studies",
 "identified_overextension": "'All hydraulic conditions' risks overgeneralizing from 2 studies; already softened by 'in some... in others' framing but should be checked against full text",
 "evidence_needed": "Full text of both studies to confirm exact site counts, I&I severity classification, and whether findings are as cleanly complementary as summarized",
 "preferred_evidence_type": "Multi-site comparative study explicitly varying hydraulic/I&I conditions",
 "preferred_study_design": "Multi-site (3+) comparison spanning a documented range of I&I severity",
 "minimum_number_of_settings": "2 minimum (met: Rainey + Darling); 3+ preferred for a 'no universal fixed factor' claim",
 "database_search_concepts": "flow normalization performance; inflow infiltration wastewater surveillance; population normalization comparison multi-site",
 "candidate_search_query": '("flow normalization" OR "population normalization") AND (wastewater) AND ("inflow and infiltration" OR "multi-site" OR "multi-community")',
 "full_text_required": "yes",
 "decision_if_unresolved": "qualify -- if full text does not confirm the complementary reading, qualify to 'these findings are not necessarily contradictory, since...' rather than asserting the synthesis as established",
 "status": "Pending full-text acquisition (both studies)"},
{"priority": "P0", "target_section": "4.2", "paragraph_id": "P4-5",
 "exact_claim": "Rainfall, infiltration, and industrial or non-domestic discharge each limit what flow normalization alone can fix... Comparative evidence shows flow normalization outperforming biomarker alternatives in some large multi-site studies... while becoming unreliable under substantial inflow and infiltration in others -- a context-dependent applicability condition, not a universal ranking.",
 "claim_type": "Cross-site generalization + performance comparison", "current_reference": "[13] Rainey et al. 2023; [3] Darling et al. 2025",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Same underlying pair as P3-9; industrial/non-domestic discharge limitation is asserted without any specific citation",
 "identified_overextension": "The industrial/non-domestic-discharge clause has NO citation at all in the condensed text -- an uncited mechanistic assertion, distinct from the Rainey/Darling pairing's evidence gap",
 "evidence_needed": "(1) Same as P3-9 for the Rainey/Darling pairing; (2) a specific citation for the industrial/non-domestic-discharge-limits-normalization claim, currently entirely uncited",
 "preferred_evidence_type": "Primary study documenting industrial/non-domestic flow contribution's effect on normalization validity",
 "preferred_study_design": "Field study in a mixed residential/industrial sewershed comparing normalization performance",
 "minimum_number_of_settings": "1 for the industrial-discharge clause specifically (currently 0)",
 "database_search_concepts": "industrial discharge wastewater normalization; non-domestic flow contribution sewer; trade waste wastewater surveillance",
 "candidate_search_query": '("industrial discharge" OR "non-domestic wastewater" OR "trade waste") AND ("wastewater surveillance" OR "wastewater normalization")',
 "full_text_required": "yes",
 "decision_if_unresolved": "remove -- if no citation can be found for the industrial/non-domestic-discharge clause specifically, remove that clause; the rainfall/infiltration portion can retain the existing Rainey/Darling citations",
 "status": "Pending targeted search (Addendum module 2); industrial-discharge clause currently has zero supporting citation"},
{"priority": "P0", "target_section": "4.3", "paragraph_id": "P4-6",
 "exact_claim": "No single population biomarker has been validated as universally reliable... Creatinine... disqualified by in-sewer instability; cotinine... confounded by geographically variable smoking prevalence; PMMoV and crAssphage... show inconsistent, often neutral-or-negative, performance across independent multi-site validation studies.",
 "claim_type": "Performance comparison, cross-study generalization",
 "current_reference": "Chen et al. 2014 (creatinine/cotinine); Maal-Bared et al. 2023, Dhiyebi et al. 2023 (PMMoV/crAssphage) -- none named inline in condensed prose",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Each named biomarker's performance pattern rests on 1-3 single-site or few-site studies per the source draft's fuller §6.4-§6.5 narrative; 'no biomarker universally validated' is this review's own synthesis, not directly demonstrated by any one source",
 "identified_overextension": "The condensed text does not name the supporting studies inline -- readers cannot trace 'PMMoV... inconsistent' to its source from the condensed prose alone (citation-attribution gap)",
 "evidence_needed": "Full text of Chen et al. 2014, Maal-Bared et al. 2023, and Dhiyebi et al. 2023 to confirm the specific site counts and performance directions summarized",
 "preferred_evidence_type": "Multi-site comparative validation studies (already the design of the 3 underlying studies)",
 "preferred_study_design": "Multi-site (10+) biomarker performance comparison against independent clinical reference data",
 "minimum_number_of_settings": "3+ (multiple biomarkers, multiple studies already implied; full text needed to confirm exact counts)",
 "database_search_concepts": "PMMoV normalization performance; crAssphage wastewater normalization; fecal indicator biomarker wastewater validation",
 "candidate_search_query": '(PMMoV OR crAssphage OR "fecal indicator") AND (wastewater) AND (normalization) AND (validation OR correlation)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain with citation restored -- add inline citations (Chen et al. 2014; Maal-Bared et al. 2023; Dhiyebi et al. 2023) to the condensed text regardless of full-text-verification outcome; narrow specific performance claims only if full text contradicts the abstract-level summary",
 "status": "Pending full-text acquisition (3 studies); immediate citation-attribution fix recommended"},
{"priority": "P0", "target_section": "4.4 / Table 2", "paragraph_id": "P4-10",
 "exact_claim": "Table 2's four rows (flow, census population, dynamic population, biomarker ratio) against corrected mechanism, required assumption, and residual uncertainty.",
 "claim_type": "Table performance judgment (consolidated)",
 "current_reference": "[3],[13] (flow rows); Chen/Maal-Bared/Dhiyebi implied for biomarker row, not cited in the table itself",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Table cells synthesize the same underlying single-study findings named in P4-3 through P4-7; the biomarker-ratio row's residual-uncertainty cell is a general synthesis not tied to any specific named study in the table",
 "identified_overextension": "Table 2 carries NO citation column at all -- a reader cannot trace any cell's claim to a specific source without cross-referencing prose elsewhere. Structural evidentiary-transparency gap in the table's own design.",
 "evidence_needed": "Same as P4-5 and P4-6 combined, since Table 2 consolidates both",
 "preferred_evidence_type": "Same as P4-5/P4-6",
 "preferred_study_design": "Same as P4-5/P4-6",
 "minimum_number_of_settings": "Varies by row -- see P4-5/P4-6",
 "database_search_concepts": "Combines Addendum modules 2 (rainfall/hydraulic), 4 (normalization biomarkers), 5 (fate matching)",
 "candidate_search_query": "See P4-5 and P4-6 queries combined",
 "full_text_required": "yes",
 "decision_if_unresolved": "qualify -- add a citation column to Table 2 regardless of full-text outcome (a table-design fix, independent of new evidence); qualify individual cells per each row's underlying claim's resolution",
 "status": "Pending full-text acquisition (aggregates P4-5/P4-6); table-design fix (citation column) can proceed independently"},
{"priority": "P0", "target_section": "5.5 / Table 3", "paragraph_id": "P5-10",
 "exact_claim": "Table 3's six model-family rows (direct mass balance, empirical regression, convolution/deconvolution, mechanistic transport-decay, Bayesian/state-space, hybrid process-informed) against identifiability requirement, dominant uncertainty, minimum validation, and failure mode.",
 "claim_type": "Table performance/validation judgment (consolidated)",
 "current_reference": "[35] Huisman et al. 2022; [44] Dai et al. 2024; [38] Ai et al. 2022 (implied); 3 of 6 rows uncited",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Only 3 of 6 rows have an explicit citation elsewhere in Part 5's prose; the mass-balance, empirical-regression, and mechanistic-transport-decay rows' cells are this review's own synthesis without a named illustrative study in the condensed text",
 "identified_overextension": "3 of 6 rows (mass balance, empirical regression, mechanistic transport-decay) have NO citation at all in the condensed draft -- same structural gap as P4-10's Table 2",
 "evidence_needed": "Named illustrative studies to properly anchor all 6 rows -- the source draft already identifies candidates (Zuccato et al. 2008 for mass balance, Schoen et al. 2022 for empirical regression, McMahan et al. 2021 for mechanistic transport-decay) that were not carried into the condensed Table 3",
 "preferred_evidence_type": "One representative primary study per model family, full text",
 "preferred_study_design": "Varies by family -- see source draft §7.4 Table 4/5 for full candidate list",
 "minimum_number_of_settings": "1 per row minimum for citation-attribution; 2+ for full generalization",
 "database_search_concepts": "WBE mass balance back-calculation; empirical regression wastewater case prediction; SEIR wastewater compartmental model",
 "candidate_search_query": '("wastewater-based epidemiology" OR WBE) AND ("mass balance" OR "back-calculation" OR "compartmental model" OR "SEIR")',
 "full_text_required": "yes",
 "decision_if_unresolved": "qualify -- restore citations for all 6 rows from the source draft's existing Table 4/5 (Zuccato et al. 2008, Schoen et al. 2022, McMahan et al. 2021 are already in the source draft's evidence base, just not carried into the condensed Table 3) -- a citation-restoration fix independent of new full-text verification",
 "status": "Pending full-text acquisition; 3-row citation-attribution gap can be partially fixed immediately by restoring existing source-draft citations"},
{"priority": "P0", "target_section": "6.1", "paragraph_id": "P6-1",
 "exact_claim": "...a recent preprint reports a sensitivity advantage for an event-detection framework over a clinical-data baseline across a large U.S. county sample (Link, Garrido, et al., 2026), but this is a single, non-peer-reviewed study set in one national context, and threshold transportability across populations and sewersheds cannot be assumed from it and must be re-validated in each new deployment context.",
 "claim_type": "Performance + cross-population generalization (already self-limited in text)",
 "current_reference": "[57] Link, Garrido et al. 2026 (medRxiv preprint)",
 "current_evidence_level": "Abstract-checked, non-peer-reviewed preprint, metadata only partially corroborated",
 "current_support_scope": "Single preprint, single country (U.S.), single disease (SARS-CoV-2) -- already explicitly flagged as single-study and non-transferable in the same sentence; the specific 281-county figure was removed from the condensed text this round as not essential to the argument",
 "identified_overextension": "The underlying source is a preprint, not a peer-reviewed publication -- per this round's rule, a preprint must not alone support a core claim. Addressed directly this round via Option C narrowing (Task 99): condensed draft §6.1 edited to an explicit 'a recent preprint reports...' framing, the specific 281-county number removed as non-essential, and single-study/non-peer-reviewed/single-national-context caveats added in the same sentence.",
 "evidence_needed": "Either (a) the formal peer-reviewed version of this preprint, or (b) a second, independent peer-reviewed study of wastewater-based event/outbreak detection performance",
 "preferred_evidence_type": "Peer-reviewed primary study",
 "preferred_study_design": "Multi-site event-detection performance evaluation against a clinical baseline",
 "minimum_number_of_settings": "2 (currently 1, and that 1 is unpublished)",
 "database_search_concepts": "wastewater outbreak detection sensitivity; event detection SARS-CoV-2 wastewater; alert threshold wastewater surveillance performance",
 "candidate_search_query": '("event detection" OR "outbreak detection" OR "alert threshold") AND (wastewater) AND (sensitivity OR "predictive value")',
 "full_text_required": "yes (for formal version if found; otherwise second independent study)",
 "decision_if_unresolved": "narrow -- Option C narrowing applied this round (verified in condensed draft §6.1); general threshold-transportability point retained as this review's own inference, decoupled from the 281-county figure, which is no longer cited in the text",
 "status": "Option C narrowing applied and verified in WBE_Review_WR_Condensed_Draft.md §6.1 this round; formal-version / independent second-study search still pending (see Full Text Request List and Search Addendum module 9)"},
{"priority": "P1", "target_section": "4.1", "paragraph_id": "P4-2",
 "exact_claim": "Recovery... and inhibition or matrix suppression... are mechanistically distinct amplitude-loss terms... which is why they require separate quality-control checks rather than one combined correction factor.",
 "claim_type": "Mechanistic + method-performance comparison", "current_reference": "Pecson et al. 2021 (referenced qualitatively, not inline-cited)",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Pecson et al. supports the interlaboratory-variability finding generally (36-SOP comparison); not cited inline in the condensed paragraph",
 "identified_overextension": "Pecson et al. is referenced only in the Claim Map, not as an inline citation in the condensed draft -- same attribution-gap pattern as P4-6",
 "evidence_needed": "Full text of Pecson et al. 2021 to confirm the 36-SOP interlaboratory finding's magnitude and whether recovery/inhibition were separately, not jointly, characterized",
 "preferred_evidence_type": "Interlaboratory comparison study",
 "preferred_study_design": "Multi-laboratory, multi-SOP comparison with recovery and inhibition measured as separate QC metrics",
 "minimum_number_of_settings": "1 (interlaboratory study inherently multi-site)",
 "database_search_concepts": "wastewater qPCR interlaboratory comparison; recovery efficiency PCR inhibition wastewater",
 "candidate_search_query": '("interlaboratory" OR "inter-laboratory") AND (wastewater) AND (recovery OR inhibition) AND (SARS-CoV-2 OR qPCR)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain with citation restored -- add inline citation to Pecson et al. 2021 regardless of full-text outcome; the six-concept taxonomy itself is this review's own framework, not dependent on this citation",
 "status": "Pending full-text acquisition; citation-attribution fix recommended immediately"},
{"priority": "P1", "target_section": "5.1", "paragraph_id": "P5-2",
 "exact_claim": "A deconvolution approach that grounds its shedding kernel in independently collected clinical data... (Huisman et al., 2022), is this evidence base's clearest example of a method deliberately designed around state observability rather than fit quality alone.",
 "claim_type": "Performance comparison, evidence-anchored", "current_reference": "[35] Huisman et al. 2022",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Huisman et al. genuinely supports the state-observability-design claim for that one study; 'no family satisfies every target' is this review's own broader synthesis",
 "identified_overextension": "None identified beyond the general single-study-generalization caution already applied throughout",
 "evidence_needed": "Full text of Huisman et al. 2022 to confirm the externally-grounded-kernel design and its actual state-observability implications as described",
 "preferred_evidence_type": "Primary methodological study",
 "preferred_study_design": "Deconvolution/back-calculation method paper with external kernel validation",
 "minimum_number_of_settings": "1 (sufficient for the specific method-design claim; full generalization not claimed)",
 "database_search_concepts": "wastewater deconvolution shedding kernel; effective reproduction number wastewater",
 "candidate_search_query": '(wastewater) AND (deconvolution OR "shedding kernel") AND ("reproduction number" OR Rt)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain -- claim is already appropriately scoped to one study; if full text contradicts, downgrade to 'was reported to' framing",
 "status": "Pending full-text acquisition"},
{"priority": "P1", "target_section": "5.2", "paragraph_id": "P5-4",
 "exact_claim": "...no formal observability analysis or synthetic-state recovery test accompanies those estimates, so the posterior's narrowness should not, by itself, be read as demonstrated observability (Dai et al., 2024).",
 "claim_type": "Model validation-tier judgment", "current_reference": "[44] Dai et al. 2024",
 "current_evidence_level": "Abstract-checked, illustrative example",
 "current_support_scope": "Dai et al. supports only the specific claim that no formal observability test was confirmed via this review's search; does not itself claim the general principle",
 "identified_overextension": "The claim that 'no formal observability analysis... accompanies those estimates' is an absence-of-evidence claim based on this review's own search not finding one -- a meaningfully weaker evidentiary basis than a positive finding",
 "evidence_needed": "Full text of Dai et al. 2024 to directly confirm whether an observability analysis is or is not present (absence claims based on abstract/search alone are the least reliable claim type)",
 "preferred_evidence_type": "Primary methodological study, full text specifically checked for a validation/observability section",
 "preferred_study_design": "Bayesian/state-space WBE model paper",
 "minimum_number_of_settings": "1",
 "database_search_concepts": "Bayesian wastewater case prediction; state-space model wastewater surveillance validation",
 "candidate_search_query": '(Bayesian OR "state-space") AND (wastewater) AND ("case count" OR prediction) AND (validation OR observability)',
 "full_text_required": "yes",
 "decision_if_unresolved": "qualify -- if full text cannot be obtained, reword from 'no formal observability analysis... accompanies' (an absence claim) to 'no formal observability analysis was identified in this review's search of the available abstract/summary' -- a precision fix independent of new evidence",
 "status": "Pending full-text acquisition; wording-precision fix recommended regardless"},
{"priority": "P1", "target_section": "5.3", "paragraph_id": "P5-6",
 "exact_claim": "...a machine-learning approach achieving useful short-horizon predictive performance across several sewersheds, evaluated on a genuine train/test split, still contains no individually interpretable parameter and no explicit latent-state representation at all... (Ai et al., 2022).",
 "claim_type": "Model validation-tier judgment", "current_reference": "[38] Ai et al. 2022 (⚠ metadata partially unresolved)",
 "current_evidence_level": "Abstract-checked, metadata incomplete",
 "current_support_scope": "Ai et al. supports the specific study-design characterization; the general principle is this review's own",
 "identified_overextension": "[38]'s own author-list metadata is unresolved (⚠ flag) -- a metadata gap layered on top of the full-text gap",
 "evidence_needed": "(1) full-text confirmation of study design; (2) independent confirmation of full author list",
 "preferred_evidence_type": "Primary ML/WBE study",
 "preferred_study_design": "Multi-community ML prediction study with explicit train/test split",
 "minimum_number_of_settings": "1 (already multi-community within the one study)",
 "database_search_concepts": "machine learning wastewater outbreak prediction; multi-community wastewater ML train test",
 "candidate_search_query": '("machine learning" OR "random forest" OR "neural network") AND (wastewater) AND (outbreak OR prediction) AND (community)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain -- claim is well-scoped already (a logical, not empirical, point); resolve the author-list metadata gap independently of the full-text question",
 "status": "Pending full-text acquisition + independent author-list re-verification"},
{"priority": "P1", "target_section": "6.2", "paragraph_id": "P6-2",
 "exact_claim": "A four-system integration of hospital, wastewater, meteorological, and internet-search data into one shared time series found a substantial subset of the fused variables correlating significantly with clinical case counts (Zhang et al., 2025), illustrating that fusion can outperform any single stream.",
 "claim_type": "Performance comparison", "current_reference": "[58] Zhang et al. 2025",
 "current_evidence_level": "Abstract-checked (metadata-verified)",
 "current_support_scope": "Single study, single city (southern China per source draft); 'illustrating that fusion can outperform any single stream' is this review's own generalization from one study",
 "identified_overextension": "'Illustrating that fusion can outperform any single stream' risks reading as a general finding when it rests on one city's data; should be checked against full text for how directly the study itself makes this comparative claim",
 "evidence_needed": "Full text of Zhang et al. 2025 to confirm the actual correlation-improvement magnitude and whether the study itself claims fusion outperforms single streams, or whether that is this review's inference",
 "preferred_evidence_type": "Primary multi-source data-fusion study",
 "preferred_study_design": "Multi-city or multi-site data-fusion comparison against single-stream baselines",
 "minimum_number_of_settings": "2 (currently 1 -- one Chinese city)",
 "database_search_concepts": "multi-source surveillance data fusion; wastewater hospital search-query integration",
 "candidate_search_query": '(wastewater) AND (fusion OR integration OR "multi-source") AND (hospital OR clinical) AND (surveillance)',
 "full_text_required": "yes",
 "decision_if_unresolved": "narrow -- if full text does not directly support the 'outperform any single stream' framing, narrow to 'in the studied Chinese city...' per the cross-city evidentiary rule",
 "status": "Pending full-text acquisition + targeted search for a second city/setting"},
{"priority": "P1", "target_section": "6.3", "paragraph_id": "P6-4",
 "exact_claim": "...non-sewered populations are structurally, not merely incidentally, invisible to this method, and a national assessment finds sewer connectivity systematically, not randomly, associated with specific demographic and geographic factors (Yu et al., 2024)... a documented instance exists of a wastewater detection being traced upstream to a specific residence (Moallef et al., 2025).",
 "claim_type": "Ethics/equity -- empirical + documented-instance", "current_reference": "[52] Yu et al. 2024; [51] Moallef et al. 2025",
 "current_evidence_level": "Abstract-checked (both metadata-verified)",
 "current_support_scope": "Yu et al. supports the connectivity-inequity finding specifically for the U.S. only; Moallef et al. supports one documented re-identification instance (already correctly singular after this round's fix), not a rate or frequency claim",
 "identified_overextension": "None remaining after this round's fix (see Phase 2B Risk Log); U.S.-only scope of Yu et al. should be made explicit if not already",
 "evidence_needed": "Full text of both studies; confirm Yu et al.'s finding is U.S.-specific and not implicitly generalized; confirm Moallef et al.'s re-identification example's actual documentation quality",
 "preferred_evidence_type": "Yu et al.: primary field/data-analysis study (already appropriate design). Moallef et al.: verify whether the re-identification example is the review's own primary finding or a citation to a third source",
 "preferred_study_design": "National infrastructure/connectivity assessment (Yu et al.); critical review methodology (Moallef et al.)",
 "minimum_number_of_settings": "Not applicable for the documented-instance claim (n=1 is the claim itself); Yu et al.'s U.S.-only scope should be flagged explicitly if ever generalized",
 "database_search_concepts": "sewer connectivity equity; wastewater surveillance health equity; wastewater re-identification privacy case",
 "candidate_search_query": '("sewer connectivity" OR "sanitation access") AND (equity OR disparities); ("wastewater surveillance") AND (privacy OR "re-identification") AND (case OR incident)',
 "full_text_required": "yes",
 "decision_if_unresolved": "qualify -- add explicit '(U.S.-specific finding)' qualifier to the Yu et al. citation if full text confirms U.S.-only scope, per this review's own cross-population generalizability rule",
 "status": "Pending full-text acquisition (both studies)"},
{"priority": "P1", "target_section": "7.2", "paragraph_id": "P7-2",
 "exact_claim": "...a national metrology working group argues standardized reporting and proficiency testing are necessary, not merely desirable, preconditions for cross-laboratory data to be used reliably in public-health decisions (Keenum et al., 2024).",
 "claim_type": "Methodological/policy argument, evidence-anchored", "current_reference": "[64] Keenum et al. 2024 (⚠ duplicated-surname flag); [63] Pagsuyoin et al. 2025",
 "current_evidence_level": "Abstract-checked",
 "current_support_scope": "Already correctly framed as 'a national metrology working group argues' (one group's position, not consensus) -- confirmed non-overextended in Phase 2B's citation audit",
 "identified_overextension": "None in the claim itself; the [64] author-list inconsistency (duplicated 'Gushgari' surname) remains an unresolved metadata gap independent of the claim's framing",
 "evidence_needed": "(1) full text of Keenum et al. 2024 to resolve the author-list duplication and confirm the position paper's actual scope/authority; (2) full text of Pagsuyoin et al. 2025",
 "preferred_evidence_type": "Position paper (already identified); independent confirmation of author list",
 "preferred_study_design": "Not applicable (position/policy paper, not an empirical study)",
 "minimum_number_of_settings": "Not applicable",
 "database_search_concepts": "wastewater surveillance standardization; interlaboratory proficiency testing wastewater; reference materials wastewater qPCR",
 "candidate_search_query": '(wastewater) AND (standardization OR "proficiency testing" OR "reference material") AND (surveillance OR qPCR)',
 "full_text_required": "yes",
 "decision_if_unresolved": "retain -- claim is already appropriately hedged; resolve the author-list metadata issue independently via a targeted re-search (not a full-text question)",
 "status": "Pending full-text acquisition + independent author-list re-verification for [64]"},
]


def main():
    with open(OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(ROWS)
    p0 = sum(1 for r in ROWS if r["priority"] == "P0")
    p1 = sum(1 for r in ROWS if r["priority"] == "P1")
    print(f"Wrote {len(ROWS)} rows to {OUT}")
    print(f"P0 (Critical): {p0}; P1 (High): {p1}")


if __name__ == "__main__":
    main()
